/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class Linter {
    public static void main(String[] args) {
        String filePath = (args.length == 0)
                ? "app/src/test/resources/gates.js"
                : args[0];
        File file = new File(filePath);
        try (Scanner sc = new Scanner(file)) {
            runLinter(sc);
        } catch (FileNotFoundException e) {
            System.out.println("File does not exist.");
        }
    }

    public static String runLinter(Scanner input) {
        String output = "";
        for(int lineNumber = 1; input.hasNextLine(); lineNumber++) {
            String line = input.nextLine();
            String result = checkSemicolonRule(lineNumber, line);
            System.out.print(result);
            output += result;
        }
        return output;
    }

    public static String checkSemicolonRule(int lineNumber, String line) {
        if (line.isEmpty()) return "";
        if (line.endsWith("{") || line.endsWith("}") || line.endsWith(";"))
            return "";
        else
            return String.format("Line %d: Missing semicolon.\n", lineNumber);
    }
}

/*
interface LinterRule {
    String runRule(int lineNumber, String line);
}

class SemicolonRule implements LinterRule {
    public String runRule(int lineNumber, String line) {
        if (line.isEmpty()) return "";
        if (line.endsWith("{") || line.endsWith("}") || line.endsWith(";"))
            return "";
        else
            return String.format("Line %d: Missing semicolon.\n", lineNumber);
    }
}
 */